export { default as Home } from './Home';
export { default as Products } from './Products';
export { default as Categories } from './Categories';
export { default as Auth } from './Auth';
export { default as Users } from './Users';
export { default as Orders } from './Orders';
export { default as Billing } from './Billing';
export { default as PaymentCard } from './PaymentCard';
export { default as Favorites } from './Favorites';
